### ISSUE TITLE
How to produce production build

### ISSUE THREAD

**Issue by brettrowberry** [fable-compiler/webpack-config-template#4]
I am just getting started with Fable. I cloned https://github.com/fable-compiler/fable2-samples. The default webpack.config.js with `npm start` does a development build. How do I produce a production build?

**Comment by alfonsogarciacaro** [comment]
The Webpack configuration in the minimal sample is not optimized for production but if you use the configuration in the fulma-demo or in this repo, by default it will assume you want a [production build when you run `webpack` instead of `webpack-dev-server`](https://github.com/fable-compiler/webpack-config-template/blob/dbe3e4464528efce50b6a17605b6a8858033cc01/webpack.config.js#L42-L44).

**Comment by MangelMaxime** [comment]
I am closing this issue as I think we want to keep the config in the repo really small.
